### ISSUE TITLE
App crashing every few minutes

### ISSUE THREAD

**Issue by AllegedlyUndead** [rasmuslos/ShelfPlayer#204]
App version 2.5.2
Database 1.1.0
Server connection: website using ngix proxy with cloudflare

Recreation: I can’t seem to pinpoint why or what’s happening when it crashes. 

My app is crashing randomly every few minutes. I tried downloading the book to the device and it’s still crashing. Once it crashes, the audio jumps back a few seconds. 

Times it has crashed:

Device screen locked
Device screen unlocked 
App open in foreground
After pausing and playing

**Comment by alabalistic** [comment]
## Probably related to my issue.
.opus files have issue playing.
Good day, I love the app, it feels really good, best purchase ever. Here is some logs and finding you might be interested in.
I realize that some books are not playing on my iphone, they work as expected on android and web ui.
I have two types of files in my library .mp3 and .opus. MP3 works fine, and snappy.
Opus is borked. When start a book I have few seconds and then it's dead for good.  My backend server logs goes in a loop quite aggressively here is the short version 


```
audiobookshelf-1  | [2025-01-30 10:33:15.953] INFO: [STREAM-CHECK] Check Files 146 of 2846 5.13% Furthest Segment: 2440
audiobookshelf-1  | [2025-01-30 10:33:16.076] WARN: File path does not exist /metadata/streams/96a22c17-d80e-41ff-8f8a-73edccf7630b/output-2641.ts
audiobookshelf-1  | [2025-01-30 10:33:16.077] INFO: Segment #2641 requested is 201 segments from latest (4:24:06) - Reset Transcode
audiobookshelf-1  | [2025-01-30 10:33:16.079] INFO: [FFMPEG] Transcode Killed
audiobookshelf-1  | [2025-01-30 10:33:16.577] INFO: Stream Reset New Start Time 4:23:36
audiobookshelf-1  | [2025-01-30 10:33:16.578] INFO: [STREAM] START STREAM - Num Segments: 2846
audiobookshelf-1  | [2025-01-30 10:33:16.578] INFO: [HlsRouter] Resetting Stream - notify client @15846s
audiobookshelf-1  | [2025-01-30 10:33:16.579] INFO: [STREAM] Starting Stream at startTime 4:23:06 (User startTime 4:23:36) and Segment #2631
audiobookshelf-1  | [2025-01-30 10:33:16.581] INFO: [INFO] FFMPEG transcoding started with command: ffmpeg -seek_timestamp 1 -f concat -safe 0 -ss 15786s -noaccurate_seek -i /metadata/streams/96a22c17-d80e-41ff-8f8a-73edccf7630b/files.txt -y -loglevel error -map 0:a -c:a aac -f hls -copyts -avoid_negative_ts make_non_negative -max_delay 5000000 -max_muxing_queue_size 2048 -hls_time 6 -hls_segment_type mpegts -start_number 2631 -hls_playlist_type vod -hls_list_size 0 -hls_allow_cache 0 -hls_segment_filename /metadata/streams/96a22c17-d80e-41ff-8f8a-73edccf7630b/output-%d.ts /metadata/streams/96a22c17-d80e-41ff-8f8a-73edccf7630b/final-output.m3u8
audiobookshelf-1  | [2025-01-30 10:33:16.581] INFO: 
audiobookshelf-1  | [2025-01-30 10:33:16.624] WARN: File path does not exist /metadata/streams/96a22c17-d80e-41ff-8f8a-73edccf7630b/output-2642.ts
audiobookshelf-1  | [2025-01-30 10:33:16.624] INFO: [HlsRouter] Stream 96a22c17-d80e-41ff-8f8a-73edccf7630b is currently resetting
audiobookshelf-1  | [2025-01-30 10:33:16.636] WARN: File path does not exist /metadata/streams/96a22c17-d80e-41ff-8f8a-73edccf7630b/output-2643.ts
audiobookshelf-1  | [2025-01-30 10:33:16.636] INFO: [HlsRouter] Stream 96a22c17-d80e-41ff-8f8a-73edccf7630b is currently resetting
# ... this goes on for another 50 lines and then repeats
```
## This is my server config

```
root@p500:/rpool/data/docker-deployments/audiobookshelf# cat compose.yml
services:
  audiobookshelf:
    image: ghcr.io/advplyr/audiobookshelf:latest
    ports:
      - 13378:80
    volumes:
      - /mnt/tank8/media/audiobooks:/audiobooks
      - /mnt/tank8/media/podcasts:/podcasts
      - ./metadata:/metadata    
      - ./config:/config
    environment:
      - TZ=Europe/Sofia
    restart: unless-stopped 
root@p500:/rpool/data/docker-deployments/audiobookshelf# 
```
## Device iphone 15,  iOS 18.1.1
